### ISSUE TITLE
“Continue to download” is not working when making a subscription from VPN app

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-services/guardian-vpn-windows#134]
#### Affected versions:
- https://drive.google.com/file/d/1P454xbrbKnvtk8JPknR3aw8gLAoykuYf/view?usp=sharing;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Steps to reproduce:
1. Download the VPN app from above link;
2. Install the VPN app;
3. Click on the “Get Started” button;
4. On the browser window opened, sign in using a new fxa account;
5. Finalize sign in and account activation;
5. On the subscription page enter valid payment details;
6. Click  “Pay now” button;
7. Click “Continue to download” button;

#### Expected result:
-  You are redirected to the download page and the VPN app is activated with success.

#### Actual result:
- User is blocked in the “Thank you”page and the VPN app does not start.

![get started-payment vpn](https://user-images.githubusercontent.com/15685960/95832842-862d0780-0d43-11eb-8e80-53dea9af71dc.gif)

**Comment by rlr** [comment]
@ValentinaPC is this consistently reproducing?

When it happens, can you check what your subscriptions show on the FxA side: https://accounts.stage.mozaws.net/settings
And then also log into the vpn site https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/ and see if you can see the Download button or the "Try Mozilla VPN" button.

**Comment by rlr** [comment]
Ohhh. I can reproduce this now. Hopefully it's something I can fix quick on our end :-D

**Comment by rlr** [comment]
Fixed https://github.com/mozilla-services/guardian-website/commit/042a863f260d5eeb86d99256f8e3155112ecb2af

Deploying to stage now.

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx81.0.2 and Windows 10 (64-bit).
Postfix video below.
![continue to download](https://user-images.githubusercontent.com/15685960/96881013-7d94a980-1486-11eb-89af-719ec2f368b5.gif)
