### ISSUE TITLE
Internet is not working on the removed device 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-services/guardian-vpn-windows#138]
#### Affected versions:
- 1.1 (last received version);

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have the VPN app installed and active on 2 devices;
- Have an FxA account with active subscription for Mozilla VPN;
- Have the second device on which you are using the VPN, opened and with VPN active.

#### Steps to reproduce:
1. Open the VPN app and click on “My devices”;
2. Click the recycle bin to remove the second device;
3. Navigate on the internet using your second device;

#### Expected result:
-  The user can navigate on the internet.

#### Actual result:
- The Internet is not working on the second (removed) device.

#### Notes:
- the issue is also reproducing on iOS.
- the issue is NOT reproducing on Android.
- the VPN app appears to be active, until an interaction with the app is made.

**Comment by chrismore** [comment]
This is not a blocker as the VPN and the kill switch is doing what it should do. We could improve the UX so that users know what the kill switch is doing its thing.

**Comment by ValentinaPC** [comment]
From an user point of view, it is a bit confusing ending up without internet while using a VPN, if no details are provided.

**Comment by ValentinaPC** [comment]
We verified this using the lasted VPN app build on 2 different Windows 10 x64 machines.
We did the following scenario:
- remove a device;
- started the chronometer on the removed device;
  - **after 12 minutes, the VPN appears still active.**
  - **the internet was not working during this time;**

@chrismore: Based on this, we can speak about a **major issue** here, that cannot be fixed with a notification.

**Comment by chrismore** [comment]
@rlr @groovecoder @flippedcoder can you review this bug and provide feedback?

**Comment by rlr** [comment]
One UX improvement we could do for this is add a warning to the device removal dialog. Right now we say:

Remove device?
Please confirm you would like to remove DEVICE-NAME
[Cancel] [Remove]


We could add a note that it will kill the internet on that device if currently connected to the VPN.

**Comment by chrismore** [comment]
@ValentinaPC did you happen to verify if this issue also exists on the version of Windows currently available to customers or only the latest internal build?

**Comment by ValentinaPC** [comment]
> 
> 
> @ValentinaPC did you happen to verify if this issue also exists on the version of Windows currently available to customers or only the latest internal build?

Did not check it, but tried to do it today, but I was blocked by: https://github.com/mozilla/fxa/issues/6728

**Comment by flippedcoder** [comment]
Other than updating the message shown to users when they remove a device, I'm not entirely sure what we can do about that without the user interacting with the app on the removed device.

*Maybe* we could have some kind of polling process running in the background to check if a device is still associated with the user and we could kill the VPN process if it's not, but that's adding another layer of threading which will probably cause other problems.

**Comment by ValentinaPC** [comment]
So, managed to check this issue on the prod build and observed the following:
- after device removal, on the removed device the internet crashes for under a minute, even if no action is made on the app.
As a conclusion we can say that this was not happening before.

**Comment by ValentinaPC** [comment]
Verified this on the latest received Mozilla VPN build using Windows 10 x64.
The internet breakdown is announced on the remove-device message.
Postfix screenshot below.
![internet off](https://user-images.githubusercontent.com/15685960/96999012-2d2c5300-153d-11eb-949a-10f330c28679.png)
