### ISSUE TITLE
Multiple VPN instances can be opened using the same account

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-services/guardian-vpn-windows#139]
#### Affected versions:
- 1.1 (last received version);

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app;
2. Click the “Get Started” button;
3. Finalize sign in using the account from prerequisites;
4. Activate the VPN;
5. Sign out from VPN;
6. Repeat STRs 2-4 3 times;

#### Expected result:
-  An instance of VPN is running. A VPN icon is displayed in the Taskbar.

#### Actual result:
- Each time the STRs from 2-4 are repeated an extra instance of VPN is opened, each having an icon in the Taskbar.

#### Notes:
- the user can activate “n” instances using the same account or different, form a total of “n+1”.
![multiple instances](https://user-images.githubusercontent.com/15685960/96422937-5aa59380-1201-11eb-9458-c496afdbc94c.png)

**Comment by chrismore** [comment]
@flippedcoder ^^

**Comment by ValentinaPC** [comment]
Verified this as fixed on the latest VPN received build using Windows 10 x64.
Postfix video below.
![mi](https://user-images.githubusercontent.com/15685960/96854937-bde33000-1464-11eb-81ee-24b62d0e0c7c.gif)
