### ISSUE TITLE
Trying to open a second instance of VPN while the first is active returns an error

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-services/guardian-vpn-windows#142]
#### Affected versions:
- 1.1 (last received version);

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app;
2. Turn on the VPN;
3. Close the VPN (minimize it in the taskbar);
4. Open a new instance of VPN;
5. Turn on the VPN;

#### Expected result:
-  The second instance replaces the first and the VPN is turned on.

#### Actual result:
- The second instance replaces the first, but the VPN is blocked.

#### Notes:
- an error message is also displayed;
- the issue is reproduced intermittently (we could not figure it out the cause)
![error second](https://user-images.githubusercontent.com/15685960/96856492-a2792480-1466-11eb-8a90-f5503d61a1dd.gif)

**Comment by flippedcoder** [comment]
I'm not sure what's going on with this one. I haven't been able to reproduce it in the last hour. I'm also not sure why you get the "Please wait while Windows configures Mozilla VPN" dialog box. The only time I've seen that dialog is when I first install the VPN.

**Comment by ValentinaPC** [comment]
Verified as fixed on the latest VPN production build, while using Windows 10 x64.
Postfix video below.
![turnon](https://user-images.githubusercontent.com/15685960/98354605-a5107800-2029-11eb-8d5f-ce6e1adaf280.gif)
