### ISSUE TITLE
VPN app freezes after sign out - sign in actions

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-services/guardian-vpn-windows#148]
#### Affected versions:
- All Firefox;

 #### Affected VPN versions:
- last VPN signed version;

#### Affected Platforms:
- Windows 10 x64;

#### Prerequisites:
- Have an FxA account with active subscriptions;

 #### Steps to reproduce:
1. Load VPN client;
2. Sign in with success;
3. Sign out from the VPN app;
3. Click the “Get Started” button from the VPN app;
4. Finalize sign;
5. Observe the VPN Win client;

#### Expected result:
- The VPN starts.

#### Actual result:
- The VPN is blocked and it can ONLY be closed using Task Manager.

#### Notes:
- The Win VPN client appears ACTIVE on another device (Android), even if it is blocked to “Get Started” screen on Win.
![freeze](https://user-images.githubusercontent.com/15685960/97993247-78235180-1dec-11eb-82e3-c59a0db1d70b.gif)

**Comment by chrismore** [comment]
I can replicate this bug on my Windows 10 machine. No way to kill the process outside of task manager or rebooting. This is a blocker for anyone gets gets logged out or tries to log out and then would have to reboot to start over if it again.

**Comment by chrismore** [comment]
@flippedcoder @rlr ^^

**Comment by ValentinaPC** [comment]
Verified this as fixed on the latest VPN build, using Windows 10 x64.
Postfix video below.
![signout](https://user-images.githubusercontent.com/15685960/98123669-d454a700-1eba-11eb-938a-d80fb34d89bb.gif)
