### ISSUE TITLE
Copying range of log lines copies last entry first

### ISSUE THREAD

**Issue by agashlin** [mozilla-services/guardian-vpn-windows#2]
STR (seen in 0.13b):

1. Open About->View log
2. Select a range of lines by clicking a line, then Shift+click an earlier line
3. Press Ctrl+C to copy the lines
4. Paste into a text editor

The last line in the range will be listed first, though the rest are in correct order.

I think this is because I clicked on the last line first. If I click on the first line in the range first, then shift+click the last line, they are copied in the correct order.

This seems to be a common issue in multi-selection, I'm guessing that an enumeration over the range isn't guaranteed to give any particular order.

**Comment by connected-crwilson** [comment]
This issue has been confirmed as fixed in the latest `master` branch on December 11, 2019. Lines copied from the application log now appear in the correct order when pasted into a text editor. Thus, the issue will now be closed.
