### ISSUE TITLE
Self-update fails to download when connected to non-US VPN server

### ISSUE THREAD

**Issue by agashlin** [mozilla-services/guardian-vpn-windows#3]
Not sure if this has been fixed since, in 0.11b the update download fails if connecting through a non-US server (I get a default of Melbourne 1):

```
2019-12-05 11:51:37.793009: [FPN] Update started
2019-12-05 11:51:40.480010: [FPN] Error code received while downloading MSI update: 451
2019-12-05 11:51:40.548009: [FPN] Could not download MSI update file.
2019-12-05 11:51:40.631009: [FPN] Update failed
```

Changing to e.g. Chicago, IL 1 allows the upgrade to go through.

I understand that the client can't be downloaded from outside the US, but this is probably something the update check should know about (especially since there's the explicit georestricted error 451).

**Comment by connected-nkozul** [comment]
We'll have another chat with the Balrog team, see if we can simply prevent the update message from being downloaded outside of the US for now as a temporary workaround. No idea how long will the georestrictions persist for, but we'll make sure we handle HTTP code 451 and provide more context in the UI.

**Comment by connected-crwilson** [comment]
QA can confirm the issue as addressed in the latest `master` branch on December 11, 2019. While users can still initiate a client update from a network connection outside of the U.S., the application will now display a more informative error message in this case, as shown in the following screenshot:

![Screenshot (175)](https://user-images.githubusercontent.com/54954290/70638723-5e42b400-1c07-11ea-8b02-5fd482ee96c2.png)

Thus, the issue will now be closed.
