### ISSUE TITLE
In post-setup "Quick Access" info screen, it's pretty weird that we show a date from 2002 in the Windows 10 taskbar tray

### ISSUE THREAD

**Issue by dholbert** [mozilla-services/guardian-vpn-windows#64]
STR:
(1) Set up to VPN app on Windows
(2) After you've done the authentication step, you should see a "Quick Access" info screen, with a screenshot of a Windows 10 taskbar tray. Take a look at that screenshot.

ACTUAL RESULTS:
The screenshot shows a date of 9.23.2002, which is nonsensical because it's (a) long before this app was ever released and (b) long before Windows 10 existed.

EXPECTED RESULTS:
Use an example-date that makes more sense in the context of a Windows 10 app, e.g. maybe a date from 2019

Here's a screenshot:
![image](https://user-images.githubusercontent.com/426803/75581109-bf677000-5a1d-11ea-897b-2a66c35df16c.png)

**Comment by tonymurphy-rgb** [comment]
https://www.google.com/search?client=firefox-b-1-d&q=firefox+release+date

**Comment by tonymurphy-rgb** [comment]
Its an Easter egg

**Comment by dholbert** [comment]
Ha! OK, fair enough.
